services:
  db: # БАЗА ДАННЫХ
    image: postgres:15 # Какой образ БД использовать
    container_name: msghub_db
    environment: # Переменные окружения
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: # Постоянное хранилище
      - postgres_data:/var/lib/postgresql/data
    networks:
      - msghub_network
    healthcheck: # Проверка работоспособности БД
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis: # Redis
    image: redis:7-alpine
    command: ["sh", "-c", "redis-server --appendonly yes --requirepass \"$REDIS_PASSWORD\""]
    container_name: msghub_redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - msghub_network
    healthcheck: # Проверка работоспособности Redis
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    volumes:
      - redis_data:/data
  
  backend: # Бэкенд
    build: # Будем собирать образ из DockerFile
      context: .
      dockerfile: Dockerfile
    container_name: msghub_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - msghub_network
    restart: unless-stopped
  
  # frontend: # Фронтенд
  #   build: 
  #     context: ./app/frontend
  #     dockerfile: Dockerfile
  #   container_name: msghub_frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - msghub_network
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  msghub_network:
    driver: bridge